name: SpaceTweet web server
description: Serves the web UI of SpaceTweet

setup: npm install
startup:
  command: node_modules/.bin/lsc app --name {{name}} --exorelay-port {{exorelay-port}} --exocom-port {{exocom-port}}
  online-text: all systems go


messages:
  sends:
    - user.get-details
    - user.delete
    - user.update
    - users.list
    - users.create
    - tweets.list
    - tweets.create
    - password-auth.authenticate
    - session.create
    - session.destroy
    - session.read
    - session.update
  receives:
    - user.details
    - user.not-found
    - user.updated
    - user.deleted
    - users.listed
    - users.created
    - password-auth.valid-credentials
    - password-auth.invalid-credentials
    - tweets.listed
    - tweets.created
    - session.created
    - session.destroyed
    - session.found
    - session.not-found
    - session.updated
