source 'https://rubygems.org'

gem 'rails', '4.2.5'

gem 'coffee-rails', path: '~/coffee-rails'
gem 'jquery-rails'
gem 'sass-rails'
gem 'sqlite3'
gem 'uglifier'

gem 'handlebars_assets', github: 'leshill/handlebars_assets'
