#!/usr/bin/env bash
set -e


# install Foreman
gem install foreman


# install dispatcher
( cd dispatcher ; rm -rf node_modules ; npm install )

# install the web server
( cd web_server ; bin/setup )
